FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    streamlit==1.37.1 \
    requests==2.32.3 \
    pillow==10.4.0

COPY frontend/ .

EXPOSE 8501

ENV STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
ENV STREAMLIT_SERVER_HEADLESS=true

CMD ["streamlit", "run", "front_end.py", "--server.port=8501", "--server.address=0.0.0.0"]
